In [17]:
import torch

a = torch.randn(1, 3)
print(f'a :\n {a}\n')

print(f'torch.max(a) :\n {torch.max(a)}')
print(torch.max(a))
print(f'')

print(f'torch.max(a,1) :\n {torch.max(a,1)}\n')
#print(torch.max(a,1))

print(f'torch.max(a,1)[1] :\n {torch.max(a,1)[1]}\n')

print(f'torch.max(a,1)[1].item() :\n {torch.max(a,1)[1].item()}\n')


print(f'torch.max(input=a, dim=1, keepdim=True, out=None) :\n {torch.max(input=a, dim=1, keepdim=True, out=None)}\n')


a :
 tensor([[-0.7480, -0.6798, -1.7237]])

torch.max(a) :
 -0.6797550320625305
tensor(-0.6798)

torch.max(a,1) :
 torch.return_types.max(
values=tensor([-0.6798]),
indices=tensor([1]))

torch.max(a,1)[1] :
 tensor([1])

torch.max(a,1)[1].item() :
 1

torch.max(input=a, dim=1, keepdim=True, out=None) :
 torch.return_types.max(
values=tensor([[-0.6798]]),
indices=tensor([[1]]))



In [23]:
b = torch.ones((4,5))

print(b.shape)

print(b.shape[0])

c = torch.ones(6)

print(c.shape)

print(c.shape[0])

torch.Size([4, 5])
4
torch.Size([6])
6


In [48]:
out = torch.rand((10,3))



print(out)

outp = torch.tensor([[0.1717, 0.0458, 0.0246], #0
        [0.1575, 0.4999, 0.1731], #1
        [0.4835, 0.9624, 0.2000], #1
        [0.4955, 0.6653, 0.7113], #2
        [0.8189, 0.6748, 0.7816], #0
        [0.9262, 0.0181, 0.9970], #2
        [0.8235, 0.4811, 0.0233], #0
        [0.2250, 0.2663, 0.1495], #1
        [0.6281, 0.3289, 0.5720], #0
        [0.8956, 0.0862, 0.6923]]) #0

actual = torch.tensor([1,1,2,0,1,0,2,0,1,0])

print(actual.shape)


def get_batch_classification_accuracy(output, truth):
    prediction = torch.max(output, 1)[1]
    size = truth.shape[0]
    percentage_correct = float(sum(prediction == truth)/size)
    return percentage_correct

pct = get_batch_classification_accuracy(outp,actual)

print(pct)

tensor([[0.2398, 0.2998, 0.5544],
        [0.0964, 0.2251, 0.1686],
        [0.9674, 0.8278, 0.0070],
        [0.2012, 0.9769, 0.9812],
        [0.6568, 0.3225, 0.7767],
        [0.0457, 0.4295, 0.3424],
        [0.9691, 0.2989, 0.1874],
        [0.2707, 0.0981, 0.5520],
        [0.8393, 0.7185, 0.6246],
        [0.4806, 0.1111, 0.8410]])
torch.Size([10])
0.20000000298023224
