In [1]:
import torch
import numpy as np

# Initializing a tensor

In [6]:
#Initializing a Tensor

#from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

#from np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [7]:
#from another tensor: retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0306, 0.8688],
        [0.9262, 0.0631]]) 



In [8]:
#With random or constant values:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4856, 0.0039, 0.6426],
        [0.3244, 0.9047, 0.7310]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

In [9]:
#Tensor attributes describe their shape, datatype, and the device on which they are stored.

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operation on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here : https://pytorch.org/docs/stable/torch.html.

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [10]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [13]:
#Standard numpy-like indexing and slicing:

tensor = torch.ones(4, 4)
print(f'tensor: {tensor}')
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining tensors You can use **torch.cat** to concatenate a sequence of tensors along a given dimension. See also **torch.stack**, another tensor joining op that is subtly different from torch.cat.

In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)
print(f"Shape of tensor: {t2.shape}")
print(f"Datatype of tensor: {t2.dtype}")
print(f"Device tensor is stored on: {t2.device}")

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
Shape of tensor: torch.Size([4, 3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [28]:
###Arithmetic operations

#print(f"tensor: {tensor}")

# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
#print(f"y1: {y1}")

y2 = tensor.matmul(tensor.T)
#print(f"y2: {y2}")

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3) ## The out param let's you choose where you want to store your operation
#print(f"y3: {y3}")


# This computes the element-wise product. z1, z2, z3 will have the same value
# https://en.wikipedia.org/wiki/Hadamard_product_(matrices)
z1 = tensor * tensor
#print(f"z1: {z1}")

z2 = tensor.mul(tensor)
#print(f"z2: {z2}")

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
#print(f"z3: {z3}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Single-element tensors 
If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [31]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

#So what is agg?
print(agg, type(agg))
#Appenrently the Sum function doesnt give back a float but a single tensor

12.0 <class 'float'>
tensor(12.) <class 'torch.Tensor'>


### In-place operations 
Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. 
For example: x.copy_(y), x.t_(), will change x.

### Note
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [32]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
